export default {
	WINDOW_RESIZE: 'WINDOW_RESIZE',
	CHANGE_AMBIENT: 'CHANGE_AMBIENT',
	OPEN_PROJECTS_MENU: 'OPEN_PROJECTS_MENU',
	CLOSE_PROJECTS_MENU: 'CLOSE_PROJECTS_MENU',

	LANDSCAPE: 'LANDSCAPE',
	PORTRAIT: 'PORTRAIT',

	BACKGROUND: {
		COLOR: 'color',
		WISTIA_VIDEO: 'wistia-video',
		FULLSCREEN_IMAGE: 'fullscreen-image',
	},

	COMPONENT: {
		FULLSCREEN_IMAGE: 'fullscreen-image',
		PARAGRAPH: 'paragraph',
		TITLE_PARAGRAPH: 'title-paragraph',
		EXTRA_MARGIN: 'extra-margin',
		WISTIA_VIDEO: 'wistia-video',
	},

	TABLET: 'tablet',
	PHONE: 'phone',
	COMPUTER: 'computer',

	WORK_PAGE_TOP_MARGIN: 74,
	BLOCK_PART_MAX_WINDOW_H_PHONE: 600,
	SMALL_TITLE_SIZE: 13,

	OVERALL_MARGIN: 30,
	GLOBAL_FONT_SIZE: 20,
	MEDIA_GLOBAL_W: 1920,
	MEDIA_GLOBAL_H: 1080,

	MEDIA_COVER_W: 768,
	MEDIA_COVER_H: 1024,

	MIN_MIDDLE_W: 960,
	MQ_XSMALL: 320,
	MQ_SMALL: 480,
	MQ_MEDIUM: 768,
	MQ_LARGE: 1024,
	MQ_XLARGE: 1280,
	MQ_XXLARGE: 1680,
}