export default {
	WINDOW_RESIZE: 'WINDOW_RESIZE',
	CHANGE_AMBIENT: 'CHANGE_AMBIENT',
	OPEN_PROJECTS_MENU: 'OPEN_PROJECTS_MENU',
	CLOSE_PROJECTS_MENU: 'CLOSE_PROJECTS_MENU',
	WORK_PAGE_SCROLL_TRIGGERED: 'WORK_PAGE_SCROLL_TRIGGERED',

	LANDSCAPE: 'LANDSCAPE',
	PORTRAIT: 'PORTRAIT',

	HOMEPAGE: 'HOMEPAGE',
	PROJECT: 'PROJECT',
	HOME_COVER: 'HOME_COVER',

	TOP: 'TOP',
	BOTTOM: 'BOTTOM',
	LEFT: 'LEFT',
	RIGHT: 'RIGHT',

	BACKGROUND: {
		COLOR: 'color',
		VIDEO: 'video',
		FULLSCREEN_IMAGE: 'fullscreen-image',
		FULLSCREEN_PATTERN: 'fullscreen-pattern',
	},

	COVER: {
		COLOR: 'color',
		VIDEO: 'video',
		FULLSCREEN_IMAGE: 'fullscreen-image',
	},

	EVENTS: {
		BACKGROUND_CHANGE_COLOR: 'background-change-color',
		TITLE_CHANGE_COLOR: 'title-change-color'
	},

	COMPONENT: {
		FULLSCREEN_IMAGE: 'fullscreen-image',
		PARAGRAPH: 'paragraph',
		TITLE_PARAGRAPH: 'title-paragraph',
		EXTRA_MARGIN: 'extra-margin',
		VIDEO: 'video',
		SLIDESHOW: 'slideshow',
		LINK: 'link',
	},

	TABLET: 'tablet',
	PHONE: 'phone',
	COMPUTER: 'computer',

	WORK_PAGE_TOP_MARGIN: 74,
	WORK_HEADER_PADDING: 220,

	BLOCK_PART_MAX_WINDOW_H_PHONE: 600,
	SMALL_TITLE_SIZE: 13,

	OVERALL_MARGIN: 30,
	MEDIA_GLOBAL_W: 1920,
	MEDIA_GLOBAL_H: 1080,

	MEDIA_COVER_W: 768,
	MEDIA_COVER_H: 1024,

	MIN_MIDDLE_W: 960,
	MQ_XSMALL: 320,
	MQ_SMALL: 480,
	MQ_MEDIUM: 768,
	MQ_LARGE: 1024,
	MQ_XLARGE: 1280,
	MQ_XXLARGE: 1680,
}