<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit2cd4e5b7f2925bc6a638770d83c7e8d5
{
    public static $prefixLengthsPsr4 = array (
        'J' => 
        array (
            'Jaybizzle\\CrawlerDetect\\' => 24,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Jaybizzle\\CrawlerDetect\\' => 
        array (
            0 => __DIR__ . '/..' . '/jaybizzle/crawler-detect/src',
        ),
    );

    public static $prefixesPsr0 = array (
        'M' => 
        array (
            'Mustache' => 
            array (
                0 => __DIR__ . '/..' . '/mustache/mustache/src',
            ),
        ),
        'B' => 
        array (
            'Bobthecow\\Bundle\\MustacheBundle' => 
            array (
                0 => __DIR__ . '/..' . '/bobthecow/mustache-bundle',
            ),
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit2cd4e5b7f2925bc6a638770d83c7e8d5::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit2cd4e5b7f2925bc6a638770d83c7e8d5::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit2cd4e5b7f2925bc6a638770d83c7e8d5::$prefixesPsr0;

        }, null, ClassLoader::class);
    }
}
